language: python

python:
    - "3.6"

install:
    - pip install -r requirements.txt

before script:
	- "psql -c 'create database foodtest_db:' -U postgres"

script:
    - pytest tests --cov=api --cov-report term-missing

after_success:
    - coveralls  
