language: python

python:
    - "3.6"

install:
    - "pip install -r requirements.txt"
    - "pip install coverage"
    - "pip install coveralls"	

before script:
	- psql -c 'create database test_db:' -U postgres

script:
    - pytest tests --cov=api --cov-report term-missing

after_success:
    - coveralls  

